### ISSUE TITLE
Expired imports to devopsfaith

### ISSUE THREAD

**Issue by zombiemcgruder** [xiachufang/krakend-ipfilter#1]
Hi, 
I was trying to use the plugin but unfortunately i didn't managed to import inside my krakend instance.

I have done a little bit of troubleshooting and maybe I've found a problem on **config.go** class

In fact the imports points to nothing:
- "github.com/devopsfaith/krakend/config"
- "github.com/devopsfaith/krakend/logging"

I am new in krakend and absolutely noob in go but maybe this is could be an issue.

Thank you

**Comment by x1ah** [comment]
@zombiemcgruder  `github.com/devopsfaith/krakend` has migrated to `https://github.com/luraproject/lura`, so go modules can't find the dependency. I will fix this soon.

**Comment by cadl** [comment]
@zombiemcgruder Hi, we released [1.0.1](https://github.com/xiachufang/krakend-ipfilter/releases/tag/v1.0.1)， you can try with it
