### ISSUE TITLE
IP filter not working

### ISSUE THREAD

**Issue by anbuanand** [xiachufang/krakend-ipfilter#3]
Hi Xia,
I put your config in Kraken, but it is not filtering - deny or allow both no effect, allowing the IPs
I saw ur same kraken config but it under extra config at root, but not working. Please let me know why it is not working.
I am using Ubuntu.

**Comment by anbuanand** [comment]
Okay Xia, i have to rebuild Kraken?  maybe that is the first requirement?

**Comment by x1ah** [comment]
@anbuanand Can you paste your config file and Curl's request log？

**Comment by x1ah** [comment]
@anbuanand And take a look at this example: https://github.com/xiachufang/krakend-ipfilter/tree/master/example 

If you are testing locally, in order to simulate the request IP address, you need to carry the `X-Real-Ip` HTTP header.
