### ISSUE TITLE
krakend ip filter not working 

### ISSUE THREAD

**Issue by rohit-raje-786** [xiachufang/krakend-ipfilter#4]
The config file is same as given in the example,I've just remove the allow array and added a single IP in deny array list. The program is running properly,but it's still allowing the IP which I've mention in the deny array list to access the endpoint.

**Comment by x1ah** [comment]
@rohit-raje-786 Look at this issue https://github.com/xiachufang/krakend-ipfilter/issues/3#issuecomment-1023244714 , it should be a similar problem, if you are testing locally, in order to simulate remote http requests, please add the `x-real-ip` http header.

**Comment by rohit-raje-786** [comment]
no I'm not running it on my local machine,it is running on VM

**Comment by x1ah** [comment]
@rohit-raje-786 Hello, what is your gin version?
