### ISSUE TITLE
嘗試導入但失敗

### ISSUE THREAD

**Issue by zaco-chen** [xiachufang/krakend-ipfilter#7]
您好
我這邊在嘗試導入krakend-ipfilter，但啟動krakeend會出現invalid ELF header，且該功能沒有作用
以下是我的相關資訊
[tomcat@test-krakend bin]$ go version
**go version go1.17.12 linux/amd64**
[tomcat@test-krakend bin]$ ./krakend version
**KrakenD Version: 2.3.0
Go Version: 1.20.3
Glibc Version: GLIBC-2.17_(centos-7)**

導入步驟:
1. 將xiachufang/krakend-ipfilter  GitClone至目錄
2. 至該目錄執行go build -o filter.so
3. 將filter.so複製到plugin目錄，並且在krakend.json導入plugin
4. 重新啟動krakend

想請問我在哪個步驟錯誤了呢，再麻煩解惑
謝謝

**Comment by x1ah** [comment]
@zaco-chen 你好，这个不需要编译成 plugin 方式来使用，参考 [example](https://github.com/xiachufang/krakend-ipfilter/tree/master/example) 里面的 main.go 加到你的中间件里，再参考 krakend.json 配置文件来进行配置。

**Comment by zaco-chen** [comment]
不好意思，不太明白main.go 加到你的中间件里這段該如何操作
能否麻煩您解惑，謝謝

**Comment by x1ah** [comment]
@zaco-chen 直接参考 README 里面的 Usage 代码样例
